apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  acessModes:
    - ReadWriteOnce
  capacity:
    storage: 1 Gi
  awsElasticBlockStorage:
    volumeID: <volumeid>
    fsType: ext4
 