apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-frontend
  template:
    metadata:
      labels:
        app: python-frontend
    spec:
      containers:
      - name: python-frontend
        image: your-dockerhub/python-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: http://python-backend-service:5000
