apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
      - name: python-backend
        image: your-dockerhub/python-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: mydb
        - name: DB_USER
          value: user
        - name: DB_PASSWORD
          value: password
